FROM circleci/node:8.17.0-stretch-browsers

# cypress support
ENV TERM: xterm

# cypress support
RUN sudo apt-get update && sudo apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2